volumes:
  grafana-data:
  prometheus-data:

services:
  sflow:
    image: docker.io/sflow/prometheus:latest
    ports:
    - "8008:8008"
    - "6343:6343/udp"

  snmp:
    image: quay.io/prometheus/snmp-exporter:latest
    ports:
    - "9116:9116"

  prometheus:
    image: quay.io/prometheus/prometheus:v3.0.0
    ports:
    - "9090:9090"
    volumes:
    - "prometheus-data:/prometheus"
    - "./prometheus.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    image: docker.io/grafana/grafana:11.3.1
    ports:
    - "3000:3000"
    volumes:
    - "grafana-data:/var/lib/grafana"
